import { prisma } from "@/lib/prisma";

export interface AutoTasksResult {
  renouvellementContrats: number;
  dealsInactifs: number;
  clientsSansInteraction: number;
  prescripteursInactifs: number;
  couvertureIncompleteDirigeant: number;
  total: number;
}

/**
 * Genere automatiquement des taches basees sur des regles metier.
 * Peut etre appele depuis le cron endpoint ou depuis le chargement du dashboard.
 */
export async function generateAutoTasks(): Promise<AutoTasksResult> {
  const results: AutoTasksResult = {
    renouvellementContrats: 0,
    dealsInactifs: 0,
    clientsSansInteraction: 0,
    prescripteursInactifs: 0,
    couvertureIncompleteDirigeant: 0,
    total: 0,
  };

  // ---------------------------------------------------------------
  // 1. Renouvellement contrat (60 jours avant dateEcheance)
  // ---------------------------------------------------------------
  const dans60Jours = new Date(Date.now() + 60 * 24 * 60 * 60 * 1000);

  const contratsARenouveler = await prisma.contrat.findMany({
    where: {
      statut: "actif",
      dateEcheance: {
        gte: new Date(),
        lte: dans60Jours,
      },
    },
    include: { client: true },
  });

  for (const contrat of contratsARenouveler) {
    const existingTask = await prisma.tache.findFirst({
      where: {
        clientId: contrat.clientId,
        type: "RENOUVELLEMENT",
        autoGenerated: true,
        statut: { in: ["a_faire", "en_cours"] },
      },
    });

    if (!existingTask) {
      await prisma.tache.create({
        data: {
          clientId: contrat.clientId,
          titre: `Preparer renouvellement ${contrat.typeProduit} pour ${contrat.client.raisonSociale}`,
          description: `Contrat ${contrat.numeroContrat ?? ""} arrive a echeance le ${contrat.dateEcheance?.toLocaleDateString("fr-FR")}. Preparer le renouvellement.`,
          type: "RENOUVELLEMENT",
          priorite: "haute",
          dateEcheance: contrat.dateEcheance ?? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
          autoGenerated: true,
          sourceAuto: "echeance_contrat",
        },
      });
      results.renouvellementContrats++;
    }
  }

  // ---------------------------------------------------------------
  // 2. Deal inactif (14 jours sans mise a jour)
  // ---------------------------------------------------------------
  const il_y_a_14_jours = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);

  const dealsInactifs = await prisma.deal.findMany({
    where: {
      etape: {
        notIn: ["SIGNATURE", "ONBOARDING", "DEVELOPPEMENT", "PERDU"],
      },
      dateMaj: {
        lt: il_y_a_14_jours,
      },
    },
    include: { client: true },
  });

  for (const deal of dealsInactifs) {
    const existingTask = await prisma.tache.findFirst({
      where: {
        clientId: deal.clientId,
        type: "RELANCE_PROSPECT",
        autoGenerated: true,
        statut: { in: ["a_faire", "en_cours"] },
      },
    });

    if (!existingTask) {
      const joursInactifs = Math.floor(
        (Date.now() - deal.dateMaj.getTime()) / (1000 * 60 * 60 * 24)
      );
      await prisma.tache.create({
        data: {
          clientId: deal.clientId,
          titre: `Relancer deal ${deal.titre}`,
          description: `Deal inactif depuis ${joursInactifs} jours (etape: ${deal.etape}). Relancer le prospect.`,
          type: "RELANCE_PROSPECT",
          priorite: "normale",
          dateEcheance: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
          autoGenerated: true,
          sourceAuto: "relance_prospect",
        },
      });
      results.dealsInactifs++;
    }
  }

  // ---------------------------------------------------------------
  // 3. Client sans interaction (6 mois)
  // ---------------------------------------------------------------
  const il_y_a_6_mois = new Date();
  il_y_a_6_mois.setMonth(il_y_a_6_mois.getMonth() - 6);

  const clientsActifs = await prisma.client.findMany({
    where: {
      statut: "client_actif",
    },
    select: {
      id: true,
      raisonSociale: true,
      taches: {
        where: {
          dateCreation: { gte: il_y_a_6_mois },
        },
        select: { id: true },
        take: 1,
      },
      contrats: {
        where: {
          dateCreation: { gte: il_y_a_6_mois },
        },
        select: { id: true },
        take: 1,
      },
    },
  });

  for (const client of clientsActifs) {
    // Si aucune tache creee et aucun contrat cree dans les 6 derniers mois
    if (client.taches.length === 0 && client.contrats.length === 0) {
      const existingTask = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          type: "FIDELISATION_CLIENT",
          autoGenerated: true,
          statut: { in: ["a_faire", "en_cours"] },
        },
      });

      if (!existingTask) {
        await prisma.tache.create({
          data: {
            clientId: client.id,
            titre: `Relance fidelisation ${client.raisonSociale}`,
            description: `Aucune interaction depuis plus de 6 mois. Prendre contact pour maintenir la relation.`,
            type: "FIDELISATION_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "fidelisation_client",
          },
        });
        results.clientsSansInteraction++;
      }
    }
  }

  // ---------------------------------------------------------------
  // 4. Prescripteur inactif (8 semaines sans recommandation)
  // ---------------------------------------------------------------
  const il_y_a_8_semaines = new Date(Date.now() - 8 * 7 * 24 * 60 * 60 * 1000);

  const prescripteursInactifs = await prisma.prescripteur.findMany({
    where: {
      statut: "actif",
      OR: [
        { derniereRecommandation: null },
        { derniereRecommandation: { lt: il_y_a_8_semaines } },
      ],
    },
  });

  for (const prescripteur of prescripteursInactifs) {
    // Pour les prescripteurs, on verifie par titre car il n'y a pas de clientId direct
    const existingTask = await prisma.tache.findFirst({
      where: {
        type: "SUIVI_PRESCRIPTEUR",
        autoGenerated: true,
        statut: { in: ["a_faire", "en_cours"] },
        titre: { contains: `${prescripteur.prenom} ${prescripteur.nom}` },
      },
    });

    if (!existingTask) {
      await prisma.tache.create({
        data: {
          titre: `Relancer prescripteur ${prescripteur.prenom} ${prescripteur.nom}`,
          description: prescripteur.derniereRecommandation
            ? `Derniere recommandation le ${prescripteur.derniereRecommandation.toLocaleDateString("fr-FR")}. Relancer pour maintenir le flux de recommandations.`
            : `Aucune recommandation enregistree. Relancer pour activer le partenariat.`,
          type: "SUIVI_PRESCRIPTEUR",
          priorite: "normale",
          dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
          autoGenerated: true,
          sourceAuto: "suivi_prescripteur",
        },
      });
      results.prescripteursInactifs++;
    }
  }

  // ---------------------------------------------------------------
  // 5. Couverture incomplete dirigeant (moins de 3 contrats)
  // ---------------------------------------------------------------
  const clientsAvecDirigeant = await prisma.client.findMany({
    where: {
      statut: "client_actif",
      dirigeant: { isNot: null },
    },
    select: {
      id: true,
      raisonSociale: true,
      dirigeant: { select: { prenom: true, nom: true } },
      contrats: {
        where: { statut: "actif" },
        select: { id: true },
      },
    },
  });

  for (const client of clientsAvecDirigeant) {
    if (client.contrats.length < 3) {
      const existingTask = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          type: "AUDIT_DIRIGEANT",
          autoGenerated: true,
          statut: { in: ["a_faire", "en_cours"] },
        },
      });

      if (!existingTask) {
        const dirigeantNom = client.dirigeant
          ? `${client.dirigeant.prenom} ${client.dirigeant.nom}`
          : "dirigeant";
        await prisma.tache.create({
          data: {
            clientId: client.id,
            titre: `Proposer audit 360° dirigeant ${dirigeantNom}`,
            description: `Seulement ${client.contrats.length} contrat(s) actif(s) pour ${client.raisonSociale}. Proposer un audit complet de couverture.`,
            type: "AUDIT_DIRIGEANT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "couverture_incomplete",
          },
        });
        results.couvertureIncompleteDirigeant++;
      }
    }
  }

  results.total =
    results.renouvellementContrats +
    results.dealsInactifs +
    results.clientsSansInteraction +
    results.prescripteursInactifs +
    results.couvertureIncompleteDirigeant;

  return results;
}
