import { prisma } from "@/lib/prisma";

// ── Types ──

export type CampagneSaisonniere = {
  mois: number;
  titre: string;
  description: string;
  filtre: string;
  action: string;
};

// ── Campagnes par defaut ──

export const CAMPAGNES: CampagneSaisonniere[] = [
  {
    mois: 1,
    titre: "Renouvellements sante collective",
    description: "Verifier effectifs, renegocier conditions",
    filtre: "SANTE_COLLECTIVE",
    action: "Verifier effectifs et conditions sante collective",
  },
  {
    mois: 3,
    titre: "Campagne defiscalisation PER",
    description: "Avant declarations fiscales, proposer PER aux dirigeants sans epargne retraite",
    filtre: "SANS_PER",
    action: "Proposer simulation PER avec economie fiscale",
  },
  {
    mois: 9,
    titre: "Rentree — mise a jour effectifs",
    description: "Nouvelles embauches = mise a jour sante collective + prevoyance",
    filtre: "SANTE_COLLECTIVE",
    action: "Contacter pour mise a jour effectifs post-rentree",
  },
  {
    mois: 10,
    titre: "Optimisation fiscale avant cloture",
    description: "Derniers versements PER/AV avant le 31 decembre",
    filtre: "PER_OU_AV",
    action: "Proposer versement complementaire avant cloture",
  },
];

// ── Detection des campagnes actives ──

export function getCampagnesActives(): CampagneSaisonniere[] {
  const moisActuel = new Date().getMonth() + 1;
  return CAMPAGNES.filter((c) => c.mois === moisActuel);
}

// ── Lancement d'une campagne : cree des taches par client cible ──

export async function lancerCampagne(campagne: CampagneSaisonniere): Promise<{ clientsCibles: number; tachesCreees: number }> {
  let clientsCibles = 0;
  let tachesCreees = 0;

  if (campagne.filtre === "SANTE_COLLECTIVE") {
    // Clients avec contrat sante collective actif
    const clients = await prisma.client.findMany({
      where: {
        statut: "client_actif",
        contrats: { some: { typeProduit: "SANTE_COLLECTIVE", statut: "actif" } },
      },
      select: { id: true, raisonSociale: true },
    });
    clientsCibles = clients.length;

    for (const client of clients) {
      const exists = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          titre: { contains: campagne.titre },
          statut: { in: ["a_faire", "en_cours"] },
        },
      });
      if (!exists) {
        await prisma.tache.create({
          data: {
            titre: `[Campagne] ${campagne.action} — ${client.raisonSociale}`,
            type: "ADMIN",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            clientId: client.id,
            autoGenerated: true,
            sourceAuto: "campagne",
          },
        });
        tachesCreees++;
      }
    }
  } else if (campagne.filtre === "SANS_PER") {
    // Clients actifs sans PER
    const clients = await prisma.client.findMany({
      where: {
        statut: "client_actif",
        contrats: { none: { typeProduit: "PER", statut: "actif" } },
      },
      select: { id: true, raisonSociale: true },
    });
    clientsCibles = clients.length;

    for (const client of clients) {
      const exists = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          titre: { contains: "PER" },
          statut: { in: ["a_faire", "en_cours"] },
        },
      });
      if (!exists) {
        await prisma.tache.create({
          data: {
            titre: `[Campagne] ${campagne.action} — ${client.raisonSociale}`,
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            clientId: client.id,
            autoGenerated: true,
            sourceAuto: "campagne",
          },
        });
        tachesCreees++;
      }
    }
  } else if (campagne.filtre === "PER_OU_AV") {
    // Clients avec PER ou AV
    const clients = await prisma.client.findMany({
      where: {
        statut: "client_actif",
        contrats: { some: { typeProduit: { in: ["PER", "ASSURANCE_VIE"] }, statut: "actif" } },
      },
      select: { id: true, raisonSociale: true },
    });
    clientsCibles = clients.length;

    for (const client of clients) {
      const exists = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          titre: { contains: campagne.titre },
          statut: { in: ["a_faire", "en_cours"] },
        },
      });
      if (!exists) {
        await prisma.tache.create({
          data: {
            titre: `[Campagne] ${campagne.action} — ${client.raisonSociale}`,
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            clientId: client.id,
            autoGenerated: true,
            sourceAuto: "campagne",
          },
        });
        tachesCreees++;
      }
    }
  }

  return { clientsCibles, tachesCreees };
}
