import { prisma } from "@/lib/prisma";

// ── Types ──

export type EtapeSequence = {
  jour: number;
  action: "email_ia" | "tache" | "auto_perdu";
  titre: string;
  type?: string; // type de tache (APPEL, ADMIN, RDV...)
  prompt?: string; // prompt IA pour generer email
  motif?: string; // motif si auto_perdu
};

// ── Sequences par defaut ──

export const SEQUENCES_DEFAUT = [
  {
    nom: "Nouveau prospect TPE/PME",
    description: "Sequence d'approche pour nouveaux prospects identifies",
    etapes: [
      { jour: 0, action: "tache", titre: "Email d'introduction personnalise", type: "ADMIN" },
      { jour: 3, action: "tache", titre: "Relancer par telephone", type: "APPEL" },
      { jour: 7, action: "tache", titre: "Email de valeur (checklist obligations employeur)", type: "ADMIN" },
      { jour: 14, action: "tache", titre: "Dernier appel ou archiver", type: "APPEL" },
      { jour: 21, action: "auto_perdu", titre: "Cloturer si pas de reponse", motif: "Pas de reponse" },
    ],
  },
  {
    nom: "Post-devis en attente",
    description: "Relance apres envoi de devis sans reponse",
    etapes: [
      { jour: 3, action: "tache", titre: "Relance douce post-devis", type: "ADMIN" },
      { jour: 7, action: "tache", titre: "Appeler pour debriefer le devis", type: "APPEL" },
      { jour: 14, action: "tache", titre: "Derniere relance avec urgence", type: "ADMIN" },
    ],
  },
  {
    nom: "Onboarding nouveau client",
    description: "Suivi post-signature pour un nouveau client",
    etapes: [
      { jour: 0, action: "tache", titre: "Email de bienvenue", type: "ADMIN" },
      { jour: 7, action: "tache", titre: "Verifier mise en place contrats", type: "ADMIN" },
      { jour: 30, action: "tache", titre: "Appel de satisfaction 1 mois", type: "APPEL" },
      { jour: 90, action: "tache", titre: "Proposer audit dirigeant / epargne", type: "RDV" },
    ],
  },
] as const;

// ── Initialisation des sequences par defaut ──

export async function initDefaultSequences(): Promise<number> {
  let created = 0;
  for (const seq of SEQUENCES_DEFAUT) {
    const exists = await prisma.sequence.findFirst({ where: { nom: seq.nom } });
    if (!exists) {
      await prisma.sequence.create({
        data: {
          nom: seq.nom,
          description: seq.description,
          etapes: JSON.stringify(seq.etapes),
        },
      });
      created++;
    }
  }
  return created;
}

// ── Inscrire un client dans une sequence ──

export async function inscrireClientSequence(clientId: string, sequenceId: string) {
  // Verifier pas deja inscrit dans cette sequence (en cours)
  const existing = await prisma.sequenceInscription.findFirst({
    where: { clientId, sequenceId, statut: "en_cours" },
  });
  if (existing) return existing;

  const sequence = await prisma.sequence.findUnique({ where: { id: sequenceId } });
  if (!sequence) throw new Error("Sequence introuvable");

  const etapes: EtapeSequence[] = JSON.parse(sequence.etapes);
  const premierJour = etapes[0]?.jour ?? 0;
  const prochaineAction = new Date(Date.now() + premierJour * 24 * 60 * 60 * 1000);

  return prisma.sequenceInscription.create({
    data: {
      sequenceId,
      clientId,
      etapeActuelle: 0,
      dateProchaineAction: prochaineAction,
    },
  });
}

// ── Traitement quotidien des sequences ──

export async function processSequences(): Promise<{ tachesCreees: number; dealsPerdu: number; terminee: number }> {
  const now = new Date();
  let tachesCreees = 0;
  let dealsPerdu = 0;
  let terminee = 0;

  // Trouver toutes les inscriptions en cours dont la prochaine action est passee
  const inscriptions = await prisma.sequenceInscription.findMany({
    where: {
      statut: "en_cours",
      dateProchaineAction: { lte: now },
    },
    include: {
      sequence: true,
      client: true,
    },
  });

  for (const insc of inscriptions) {
    const etapes: EtapeSequence[] = JSON.parse(insc.sequence.etapes);
    const etape = etapes[insc.etapeActuelle];

    if (!etape) {
      // Plus d'etapes, terminer
      await prisma.sequenceInscription.update({
        where: { id: insc.id },
        data: { statut: "terminee" },
      });
      terminee++;
      continue;
    }

    // Executer l'action de l'etape
    if (etape.action === "tache") {
      await prisma.tache.create({
        data: {
          titre: `[Seq] ${etape.titre} — ${insc.client.raisonSociale}`,
          type: etape.type ?? "AUTRE",
          priorite: "normale",
          dateEcheance: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
          clientId: insc.clientId,
          autoGenerated: true,
          sourceAuto: "sequence",
        },
      });
      tachesCreees++;
    } else if (etape.action === "auto_perdu") {
      // Marquer les deals ouverts de ce client comme perdus
      const dealsOuverts = await prisma.deal.findMany({
        where: {
          clientId: insc.clientId,
          etape: { notIn: ["SIGNATURE", "ONBOARDING", "DEVELOPPEMENT", "PERDU"] },
        },
      });
      for (const deal of dealsOuverts) {
        await prisma.deal.update({
          where: { id: deal.id },
          data: {
            etape: "PERDU",
            motifPerte: etape.motif ?? "Pas de reponse (sequence auto)",
          },
        });
        dealsPerdu++;
      }
    }

    // Avancer a l'etape suivante
    const nextIndex = insc.etapeActuelle + 1;
    const nextEtape = etapes[nextIndex];

    if (nextEtape) {
      const joursJusquaProchaine = nextEtape.jour - etape.jour;
      const prochaine = new Date(Date.now() + joursJusquaProchaine * 24 * 60 * 60 * 1000);
      await prisma.sequenceInscription.update({
        where: { id: insc.id },
        data: { etapeActuelle: nextIndex, dateProchaineAction: prochaine },
      });
    } else {
      await prisma.sequenceInscription.update({
        where: { id: insc.id },
        data: { statut: "terminee" },
      });
      terminee++;
    }
  }

  return { tachesCreees, dealsPerdu, terminee };
}
