"use client";

import { useState } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Save,
  Check,
  X,
  Trash2,
  ExternalLink,
  Mail,
  Calendar,
  Building2,
} from "lucide-react";
import { TYPES_TACHE, PRIORITES } from "@/lib/constants";
import {
  updateTache,
  markTacheDone,
  cancelTache,
  deleteTache,
} from "@/app/(app)/relances/actions";
import type { TacheWithClient } from "@/types";
import { format, isBefore, isToday, startOfDay } from "date-fns";
import { fr } from "date-fns/locale";
import Link from "next/link";

type Props = {
  tache: TacheWithClient;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  clients: { id: string; raisonSociale: string }[];
  users: { id: string; prenom: string; nom: string }[];
};

export function TacheDetailSheet({
  tache,
  open,
  onOpenChange,
  clients,
  users,
}: Props) {
  const [saving, setSaving] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);

  const [titre, setTitre] = useState(tache.titre);
  const [description, setDescription] = useState(tache.description || "");
  const [type, setType] = useState(tache.type);
  const [priorite, setPriorite] = useState(tache.priorite);
  const [dateEcheance, setDateEcheance] = useState(
    format(new Date(tache.dateEcheance), "yyyy-MM-dd")
  );
  const [clientId, setClientId] = useState(tache.clientId || "");
  const [assigneA, setAssigneA] = useState(tache.assigneA || "");

  const prioriteConfig = PRIORITES.find((p) => p.id === tache.priorite);
  const typeConfig = TYPES_TACHE.find((t) => t.id === tache.type);
  const isOverdue =
    isBefore(tache.dateEcheance, startOfDay(new Date())) &&
    !isToday(tache.dateEcheance);

  async function handleSave() {
    setSaving(true);
    try {
      const formData = new FormData();
      formData.set("titre", titre);
      formData.set("description", description);
      formData.set("type", type);
      formData.set("priorite", priorite);
      formData.set("dateEcheance", dateEcheance);
      formData.set("clientId", clientId);
      formData.set("assigneA", assigneA);
      await updateTache(tache.id, formData);
      onOpenChange(false);
    } finally {
      setSaving(false);
    }
  }

  async function handleMarkDone() {
    await markTacheDone(tache.id);
    onOpenChange(false);
  }

  async function handleCancel() {
    await cancelTache(tache.id);
    onOpenChange(false);
  }

  async function handleDelete() {
    await deleteTache(tache.id);
    onOpenChange(false);
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-[480px] max-w-[95vw] flex flex-col p-0">
        {/* Header */}
        <SheetHeader className="px-5 pt-5 pb-3 border-b border-border">
          <div className="flex items-start justify-between gap-3">
            <div className="min-w-0">
              <SheetTitle className="text-[15px] font-bold text-foreground truncate">
                {tache.titre}
              </SheetTitle>
              <SheetDescription className="flex items-center gap-2 mt-1">
                <Badge variant="outline" className="text-[10px]">
                  {typeConfig?.label ?? tache.type}
                </Badge>
                <Badge
                  variant="outline"
                  style={{
                    borderColor: prioriteConfig?.color,
                    color: prioriteConfig?.color,
                  }}
                  className="text-[10px]"
                >
                  {prioriteConfig?.label ?? tache.priorite}
                </Badge>
                {tache.autoGenerated && tache.emailId && (
                  <Badge
                    variant="secondary"
                    className="text-[10px] gap-0.5 bg-cyan-50 text-cyan-700 border-cyan-200"
                  >
                    <Mail className="h-2.5 w-2.5" />
                    Email
                  </Badge>
                )}
                {tache.autoGenerated && !tache.emailId && (
                  <Badge variant="secondary" className="text-[10px]">
                    Auto
                  </Badge>
                )}
                {isOverdue && (
                  <Badge variant="destructive" className="text-[10px]">
                    En retard
                  </Badge>
                )}
              </SheetDescription>
            </div>
          </div>
        </SheetHeader>

        {/* Content — scrollable */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Quick info bar */}
          <div className="bg-muted/50 rounded-lg p-3 flex items-center gap-4 text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <Calendar className="h-3 w-3" />
              {isToday(tache.dateEcheance)
                ? "Aujourd'hui"
                : format(tache.dateEcheance, "dd MMM yyyy", { locale: fr })}
            </span>
            {tache.client && (
              <Link
                href={`/clients/${tache.client.id}`}
                className="flex items-center gap-1 text-primary hover:underline"
              >
                <Building2 className="h-3 w-3" />
                {tache.client.raisonSociale}
                <ExternalLink className="h-2.5 w-2.5" />
              </Link>
            )}
            <span>
              Cree le {format(tache.dateCreation, "dd MMM yyyy", { locale: fr })}
            </span>
          </div>

          {/* Editable fields */}
          <div className="space-y-3">
            <div>
              <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                Titre
              </Label>
              <Input
                value={titre}
                onChange={(e) => setTitre(e.target.value)}
                className="text-sm"
              />
            </div>

            <div>
              <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                Notes / Contexte
              </Label>
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={4}
                className="text-sm"
                placeholder="Ajoutez du contexte, des notes de suivi..."
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                  Type
                </Label>
                <Select value={type} onValueChange={setType}>
                  <SelectTrigger className="text-sm h-9">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {TYPES_TACHE.map((t) => (
                      <SelectItem key={t.id} value={t.id}>
                        {t.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                  Priorite
                </Label>
                <Select value={priorite} onValueChange={setPriorite}>
                  <SelectTrigger className="text-sm h-9">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {PRIORITES.map((p) => (
                      <SelectItem key={p.id} value={p.id}>
                        {p.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                  Echeance
                </Label>
                <Input
                  type="date"
                  value={dateEcheance}
                  onChange={(e) => setDateEcheance(e.target.value)}
                  className="text-sm h-9"
                />
              </div>

              <div>
                <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                  Client
                </Label>
                <Select value={clientId} onValueChange={setClientId}>
                  <SelectTrigger className="text-sm h-9">
                    <SelectValue placeholder="Aucun client" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">Aucun</SelectItem>
                    {clients.map((c) => (
                      <SelectItem key={c.id} value={c.id}>
                        {c.raisonSociale}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            {users.length > 0 && (
              <div>
                <Label className="text-[11px] font-semibold text-muted-foreground mb-1 block">
                  Assigne a
                </Label>
                <Select value={assigneA} onValueChange={setAssigneA}>
                  <SelectTrigger className="text-sm h-9">
                    <SelectValue placeholder="Non assigne" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">Non assigne</SelectItem>
                    {users.map((u) => (
                      <SelectItem key={u.id} value={u.id}>
                        {u.prenom} {u.nom}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          {/* Auto-generation metadata */}
          {tache.autoGenerated && (
            <div className="bg-muted/40 rounded-lg p-3 border border-border">
              <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-1.5">
                Generation automatique
              </p>
              <div className="text-xs text-muted-foreground space-y-0.5">
                {tache.sourceAuto && (
                  <p>
                    Source : <span className="text-foreground">{tache.sourceAuto}</span>
                  </p>
                )}
                {tache.raisonFermeture && (
                  <p>
                    Raison :{" "}
                    <span className="text-foreground">{tache.raisonFermeture}</span>
                  </p>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Footer — actions */}
        <div className="px-5 py-3 border-t border-border flex gap-2">
          {confirmDelete ? (
            <div className="flex items-center gap-2 flex-1">
              <span className="text-xs text-red-600 font-medium">
                Supprimer cette tache ?
              </span>
              <Button
                variant="outline"
                size="sm"
                className="h-7 text-xs"
                onClick={() => setConfirmDelete(false)}
              >
                Non
              </Button>
              <Button
                variant="destructive"
                size="sm"
                className="h-7 text-xs"
                onClick={handleDelete}
              >
                Oui
              </Button>
            </div>
          ) : (
            <>
              <Button
                variant="ghost"
                size="sm"
                className="text-muted-foreground hover:text-destructive"
                onClick={() => setConfirmDelete(true)}
                title="Supprimer"
              >
                <Trash2 className="h-3.5 w-3.5" />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="text-muted-foreground hover:text-orange-500"
                onClick={handleCancel}
                title="Annuler la tache"
              >
                <X className="h-3.5 w-3.5 mr-1" />
                <span className="text-xs">Annuler</span>
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="text-muted-foreground hover:text-green-600"
                onClick={handleMarkDone}
                title="Marquer terminee"
              >
                <Check className="h-3.5 w-3.5 mr-1" />
                <span className="text-xs">Terminee</span>
              </Button>
              <Button
                onClick={handleSave}
                disabled={saving}
                className="flex-1"
                size="sm"
              >
                <Save className="h-3.5 w-3.5 mr-1.5" />
                {saving ? "..." : "Enregistrer"}
              </Button>
            </>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
