"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Check, Trash2, Plus, Mail, Pencil, X } from "lucide-react";
import { TYPES_TACHE, PRIORITES } from "@/lib/constants";
import { markTacheDone, cancelTache, deleteTache } from "@/app/(app)/relances/actions";
import { TacheForm } from "./TacheForm";
import { TacheDetailSheet } from "./TacheDetailSheet";
import type { TacheWithClient } from "@/types";
import { format, isBefore, isToday, startOfDay } from "date-fns";
import { fr } from "date-fns/locale";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type Props = {
  taches: TacheWithClient[];
  clients: { id: string; raisonSociale: string }[];
  users: { id: string; prenom: string; nom: string }[];
};

export function TacheList({ taches, clients, users }: Props) {
  const [showForm, setShowForm] = useState(false);
  const [editingTache, setEditingTache] = useState<TacheWithClient | null>(null);
  const [selectedTache, setSelectedTache] = useState<TacheWithClient | null>(null);
  const [filterType, setFilterType] = useState<string>("all");
  const [filterPriorite, setFilterPriorite] = useState<string>("all");

  const now = startOfDay(new Date());

  const filtered = taches.filter((t) => {
    if (filterType !== "all" && t.type !== filterType) return false;
    if (filterPriorite !== "all" && t.priorite !== filterPriorite) return false;
    return true;
  });

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex gap-3">
          <Select value={filterType} onValueChange={setFilterType}>
            <SelectTrigger className="w-[160px]">
              <SelectValue placeholder="Type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Tous les types</SelectItem>
              {TYPES_TACHE.map((t) => (
                <SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select value={filterPriorite} onValueChange={setFilterPriorite}>
            <SelectTrigger className="w-[140px]">
              <SelectValue placeholder="Priorite" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Toutes</SelectItem>
              {PRIORITES.map((p) => (
                <SelectItem key={p.id} value={p.id}>{p.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <Button size="sm" onClick={() => setShowForm(true)}>
          <Plus className="h-4 w-4 mr-2" />
          Nouvelle tache
        </Button>
      </div>

      {filtered.length === 0 ? (
        <p className="text-sm text-muted-foreground text-center py-8">
          Aucune tache a afficher
        </p>
      ) : (
        <div className="space-y-2">
          {filtered.map((tache) => {
            const prioriteConfig = PRIORITES.find((p) => p.id === tache.priorite);
            const typeConfig = TYPES_TACHE.find((t) => t.id === tache.type);
            const isOverdue = isBefore(tache.dateEcheance, now) && !isToday(tache.dateEcheance);

            return (
              <div
                key={tache.id}
                role="button"
                tabIndex={0}
                className="cursor-pointer"
                onClick={() => setSelectedTache(tache)}
                onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") setSelectedTache(tache); }}
              >
              <Card
                className={`transition-all hover:shadow-sm ${isOverdue ? "border-red-300" : ""} ${selectedTache?.id === tache.id ? "border-primary/40 bg-primary/[0.02]" : ""}`}
              >
                <CardContent className="py-3 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7 text-muted-foreground hover:text-green-600"
                      onClick={(e) => { e.stopPropagation(); markTacheDone(tache.id); }}
                    >
                      <Check className="h-4 w-4" />
                    </Button>
                    <div>
                      <div className="flex items-center gap-2">
                        <p className="font-medium text-sm">{tache.titre}</p>
                        <Badge variant="outline" className="text-[10px]">
                          {typeConfig?.label}
                        </Badge>
                        {tache.autoGenerated && tache.emailId && (
                          <Badge variant="secondary" className="text-[10px] gap-0.5 bg-cyan-50 text-cyan-700 border-cyan-200">
                            <Mail className="h-2.5 w-2.5" />
                            Email
                          </Badge>
                        )}
                        {tache.autoGenerated && !tache.emailId && (
                          <Badge variant="secondary" className="text-[10px]">Auto</Badge>
                        )}
                        {tache.autoFermee && (
                          <Badge variant="secondary" className="text-[10px] gap-0.5 bg-gray-100 text-gray-500 border-gray-200" title={tache.raisonFermeture || "Auto-fermee"}>Auto-fermee</Badge>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {tache.client?.raisonSociale ?? "Sans client"}
                        {" — "}
                        <span className={isOverdue ? "text-red-600 font-medium" : ""}>
                          {isToday(tache.dateEcheance)
                            ? "Aujourd'hui"
                            : format(tache.dateEcheance, "dd MMM yyyy", { locale: fr })}
                        </span>
                      </p>
                      {tache.description && (
                        <p className="text-[11px] text-muted-foreground/70 mt-0.5 line-clamp-1 italic">
                          {tache.description}
                        </p>
                      )}
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <Badge
                      variant="outline"
                      style={{ borderColor: prioriteConfig?.color, color: prioriteConfig?.color }}
                    >
                      {prioriteConfig?.label}
                    </Badge>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7 text-muted-foreground hover:text-orange-500"
                      title="Annuler cette tâche"
                      onClick={(e) => { e.stopPropagation(); cancelTache(tache.id); }}
                    >
                      <X className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7 text-muted-foreground hover:text-blue-600"
                      onClick={(e) => { e.stopPropagation(); setEditingTache(tache); }}
                    >
                      <Pencil className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7 text-muted-foreground hover:text-destructive"
                      onClick={(e) => { e.stopPropagation(); deleteTache(tache.id); }}
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
              </div>
            );
          })}
        </div>
      )}

      {/* Dialog creation */}
      {showForm && (
        <TacheForm
          open={showForm}
          onClose={() => setShowForm(false)}
          clients={clients}
          users={users}
        />
      )}

      {/* Dialog edition */}
      {editingTache && (
        <TacheForm
          open={!!editingTache}
          onClose={() => setEditingTache(null)}
          clients={clients}
          users={users}
          tache={editingTache}
        />
      )}

      {/* Detail sheet */}
      {selectedTache && (
        <TacheDetailSheet
          tache={selectedTache}
          open={!!selectedTache}
          onOpenChange={(open) => { if (!open) setSelectedTache(null); }}
          clients={clients}
          users={users}
        />
      )}
    </div>
  );
}
