import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// ── Types ──

interface InboxZeroPayload {
  from: string;
  subject: string;
  body: string;
  messageId: string;
  threadId: string;
  label?: string;
  date?: string;
}

// ── Helpers ──

function extractEmailAddress(from: string): string {
  const match = from.match(/<([^>]+)>/);
  return (match ? match[1] : from).toLowerCase().trim();
}

function extractSenderName(from: string): string {
  const match = from.match(/^([^<]+)\s*</);
  if (match) return match[1].trim();
  const emailMatch = from.match(/^([^@]+)@/);
  return emailMatch ? emailMatch[1] : from;
}

const INSURANCE_KEYWORDS = [
  "contrat", "police", "sinistre", "devis", "cotisation", "prime",
  "mutuelle", "prévoyance", "santé", "retraite", "assurance",
  "courtage", "résiliation", "avenant", "souscription", "adhésion",
  "garantie", "attestation", "rcpro", "protection juridique", "madelin",
];

function classifyPertinence(
  hasClient: boolean,
  sujet: string,
  extrait: string | null,
): { pertinence: string; scoreRelevance: number } {
  let score = 0;
  if (hasClient) score += 50;
  const text = `${sujet} ${extrait ?? ""}`.toLowerCase();
  if (INSURANCE_KEYWORDS.some((kw) => text.includes(kw))) score += 20;

  let pertinence = "normal";
  if (hasClient) pertinence = "client";
  else if (score >= 20) pertinence = "important";

  return { pertinence, scoreRelevance: Math.min(100, score) };
}

// ── Auth ──

function verifyAuth(req: NextRequest): boolean {
  const secret = process.env.INBOX_ZERO_WEBHOOK_SECRET;
  if (!secret) return false;

  const authHeader = req.headers.get("authorization");
  if (!authHeader) return false;

  const token = authHeader.replace(/^Bearer\s+/i, "");
  return token === secret;
}

// ── GET healthcheck ──

export async function GET() {
  return NextResponse.json({ status: "ok", service: "inbox-zero-webhook" });
}

// ── POST webhook ──

export async function POST(req: NextRequest) {
  // 1. Auth
  if (!verifyAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // 2. Parse payload
  let payload: InboxZeroPayload;
  try {
    payload = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { from, subject, body, messageId, threadId, label, date } = payload;

  if (!from || !subject || !messageId || !threadId) {
    return NextResponse.json(
      { error: "Missing required fields: from, subject, messageId, threadId" },
      { status: 400 },
    );
  }

  // 3. Deduplicate by gmailId
  const existing = await prisma.email.findUnique({ where: { gmailId: messageId } });
  if (existing) {
    return NextResponse.json({ status: "duplicate", emailId: existing.id });
  }

  // 4. Resolve userId
  const userId = process.env.DEFAULT_USER_ID;
  if (!userId) {
    return NextResponse.json({ error: "DEFAULT_USER_ID not configured" }, { status: 500 });
  }

  // 5. Match client by sender email
  const senderAddr = extractEmailAddress(from);
  const client = await prisma.client.findFirst({
    where: {
      OR: [
        { email: { equals: senderAddr, mode: "insensitive" } },
        { email: { contains: senderAddr.split("@")[0], mode: "insensitive" } },
      ],
    },
    select: { id: true },
  });
  const matchedClientId = client?.id ?? null;

  // 6. Classify
  const extrait = body ? body.substring(0, 2000) : null;
  const { pertinence, scoreRelevance } = classifyPertinence(!!matchedClientId, subject, extrait);

  // 7. Create email in DB
  const email = await prisma.email.create({
    data: {
      userId,
      gmailId: messageId,
      threadId,
      sujet: subject,
      expediteur: from,
      destinataires: "",
      dateEnvoi: date ? new Date(date) : new Date(),
      extrait,
      direction: "entrant",
      pertinence,
      scoreRelevance,
      clientId: matchedClientId,
      analyseStatut: "pending",
    },
  });

  // 8. Update client last interaction
  if (matchedClientId) {
    await prisma.client.update({
      where: { id: matchedClientId },
      data: { derniereInteraction: email.dateEnvoi },
    });
  }

  // 9. Create urgent task if label "Urgent"
  if (label?.toLowerCase() === "urgent") {
    const senderName = extractSenderName(from);
    const tomorrow9am = new Date();
    tomorrow9am.setDate(tomorrow9am.getDate() + 1);
    tomorrow9am.setHours(9, 0, 0, 0);

    await prisma.tache.create({
      data: {
        titre: `URGENT — ${senderName} : ${subject}`,
        type: "RELANCE_PROSPECT",
        priorite: "haute",
        dateEcheance: tomorrow9am,
        clientId: matchedClientId,
        emailId: email.id,
        autoGenerated: true,
        sourceAuto: "auto_email_ia",
      },
    });
  }

  // 10. Increment prescripteur counter if label "Prescripteur"
  if (label?.toLowerCase() === "prescripteur") {
    const prescripteur = await prisma.prescripteur.findFirst({
      where: { email: { equals: senderAddr, mode: "insensitive" } },
      select: { id: true },
    });

    if (prescripteur) {
      await prisma.prescripteur.update({
        where: { id: prescripteur.id },
        data: {
          dossiersEnvoyes: { increment: 1 },
          derniereRecommandation: new Date(),
        },
      });
    }
  }

  return NextResponse.json({
    status: "created",
    emailId: email.id,
    clientMatched: !!matchedClientId,
    label: label ?? null,
  });
}
