import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { withN8nAuth } from "../middleware";

async function handler(req: Request) {
  const body = await req.json();

  const {
    emailId,
    analyseIA,
    clientId,
    resumeIA,
    urgence,
    typeEmail,
    actionRequise,
    reponseSuggeree,
    dealUpdateSuggestion,
    produitsMentionnes,
  } = body as {
    emailId: string;
    analyseIA: Record<string, unknown>;
    clientId?: string;
    resumeIA?: string;
    urgence?: string;
    typeEmail?: string;
    actionRequise?: boolean;
    reponseSuggeree?: string;
    dealUpdateSuggestion?: Record<string, unknown>;
    produitsMentionnes?: string[];
  };

  if (!emailId) {
    return NextResponse.json({ error: "emailId is required" }, { status: 400 });
  }

  const email = await prisma.email.findUnique({ where: { id: emailId } });
  if (!email) {
    return NextResponse.json({ error: "Email not found" }, { status: 404 });
  }

  // Update email with analysis results
  await prisma.email.update({
    where: { id: emailId },
    data: {
      analyseIA: JSON.stringify(analyseIA),
      resume: resumeIA ?? null,
      urgence: urgence ?? null,
      typeEmail: typeEmail ?? null,
      actionRequise: actionRequise ?? false,
      actionTraitee: false,
      reponseProposee: reponseSuggeree ?? null,
      analyseStatut: "analyse",
      clientId: clientId ?? email.clientId,
      dealUpdateSuggestion: dealUpdateSuggestion
        ? JSON.stringify(dealUpdateSuggestion)
        : null,
      produitsMentionnes: produitsMentionnes
        ? JSON.stringify(produitsMentionnes)
        : null,
    },
  });

  // Update client derniereInteraction if linked
  const resolvedClientId = clientId ?? email.clientId;
  if (resolvedClientId) {
    await prisma.client.update({
      where: { id: resolvedClientId },
      data: { derniereInteraction: new Date() },
    });
  }

  // Auto-create task if action required
  if (actionRequise) {
    const actionSuggeree =
      typeof analyseIA.actionSuggeree === "string"
        ? analyseIA.actionSuggeree
        : "Traiter email";

    await prisma.tache.create({
      data: {
        titre: actionSuggeree,
        type: "RELANCE_PROSPECT",
        priorite: urgence === "haute" ? "haute" : "normale",
        dateEcheance: new Date(
          Date.now() + (urgence === "haute" ? 1 : 7) * 24 * 60 * 60 * 1000,
        ),
        clientId: resolvedClientId ?? null,
        emailId,
        autoGenerated: true,
        sourceAuto: "n8n_analyse",
      },
    });
  }

  revalidatePath("/emails");

  return NextResponse.json({ success: true, emailId });
}

export const POST = withN8nAuth(handler);
