import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { withN8nAuth } from "../middleware";
import { matchClientByEmail, extractEmailAddress } from "@/lib/email/sync";
import { buildOAuth2Client, createGmailDraft } from "@/lib/email/gmail";

// POST /api/n8n/emails — Store analysis result from n8n WF05v2
async function handler(req: Request) {
  const body = await req.json();
  const { emailId } = body as { emailId: string };

  if (!emailId) {
    return NextResponse.json({ error: "emailId is required" }, { status: 400 });
  }

  const email = await prisma.email.findUnique({ where: { id: emailId } });
  if (!email) {
    return NextResponse.json({ error: "Email not found" }, { status: 404 });
  }

  const {
    type, urgence, resume, sentiment, actionRequise, actionSuggeree,
    draftReply, clientMatch, produitsMentionnes, expediteurNom,
    expediteurEntreprise, contratMentionne,
  } = body as {
    type?: string; urgence?: string; resume?: string; sentiment?: string;
    actionRequise?: boolean; actionSuggeree?: string; draftReply?: string;
    clientMatch?: { found: boolean; clientId?: string; clientName?: string; confidence?: string };
    produitsMentionnes?: string[]; expediteurNom?: string;
    expediteurEntreprise?: string; contratMentionne?: string;
  };

  let resolvedClientId = email.clientId;
  if (clientMatch?.clientId) {
    resolvedClientId = clientMatch.clientId;
  } else if (!resolvedClientId) {
    resolvedClientId = await matchClientByEmail(email.expediteur);
  }

  const updateData: Record<string, unknown> = {
    resume: resume ?? null,
    typeEmail: type ?? null,
    urgence: urgence ?? null,
    sentiment: sentiment ?? null,
    actionRequise: actionRequise ?? false,
    actionTraitee: false,
    reponseProposee: draftReply ?? null,
    analyseStatut: "analyse",
    clientId: resolvedClientId,
    analyseIA: JSON.stringify(body),
    produitsMentionnes: produitsMentionnes?.length ? JSON.stringify(produitsMentionnes) : null,
    actionsItems: actionSuggeree ? JSON.stringify([actionSuggeree]) : null,
  };

  // Phase 3: Auto-create Gmail draft for commercial emails with draftReply
  const isCommercial = type && ["client", "prospect", "prescripteur"].includes(type);
  if (draftReply && isCommercial && email.direction === "entrant") {
    try {
      const connection = await prisma.gmailConnection.findUnique({
        where: { userId: email.userId },
      });
      if (connection) {
        const oauth2Client = buildOAuth2Client();
        oauth2Client.setCredentials({
          access_token: connection.accessToken,
          refresh_token: connection.refreshToken,
          expiry_date: connection.tokenExpiry.getTime(),
        });
        const toAddress = extractEmailAddress(email.expediteur);
        const draftId = await createGmailDraft(
          oauth2Client, toAddress, email.sujet, draftReply, email.threadId,
        );
        updateData.gmailDraftId = draftId;
        updateData.draftStatut = "brouillon";
      }
    } catch (err) {
      console.error("[n8n/emails] Auto-draft creation error:", err);
      // Non-blocking: don't fail the analysis storage
    }
  }

  await prisma.email.update({
    where: { id: emailId },
    data: updateData,
  });

  if (resolvedClientId) {
    await prisma.client.update({
      where: { id: resolvedClientId },
      data: { derniereInteraction: new Date() },
    });
  }

  // Phase 4: Auto-create "Répondre" task for inbound commercial emails
  if (isCommercial && email.direction === "entrant") {
    try {
      // Anti-doublon: check no existing reply task for this email
      const existingTask = await prisma.tache.findFirst({
        where: { emailId, sourceAuto: "email_reponse_attendue", statut: { in: ["a_faire", "en_cours"] } },
      });
      if (!existingTask) {
        const senderName = expediteurNom || email.expediteur.split("@")[0];
        const senderEmail = extractEmailAddress(email.expediteur);
        const ECHEANCE_JOURS: Record<string, number> = { haute: 1, normale: 3, basse: 7 };
        const jours = ECHEANCE_JOURS[urgence ?? "normale"] ?? 3;

        await prisma.tache.create({
          data: {
            titre: `Répondre à ${senderName} (${senderEmail})`,
            description: `Email: "${email.sujet}"`,
            type: "RELANCE_PROSPECT",
            priorite: urgence === "haute" ? "haute" : "normale",
            dateEcheance: new Date(Date.now() + jours * 24 * 60 * 60 * 1000),
            clientId: resolvedClientId,
            emailId,
            autoGenerated: true,
            sourceAuto: "email_reponse_attendue",
          },
        });
      }
    } catch (err) {
      console.error("[n8n/emails] Auto-task creation error:", err);
    }
  }

  revalidatePath("/emails");
  revalidatePath("/relances");
  revalidatePath("/clients");

  return NextResponse.json({ success: true, emailId, clientId: resolvedClientId, type: type ?? "autre", urgence: urgence ?? "normale", actionRequise: actionRequise ?? false, expediteurNom: expediteurNom ?? null, draftReply: draftReply ?? null, expediteur: body.expediteur ?? null, sujet: body.sujet ?? null, direction: body.direction ?? null });
}

export const POST = withN8nAuth(handler);
