import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { withN8nAuth } from "../middleware";

/**
 * POST /api/n8n/email-analysis
 *
 * Dedicated endpoint for n8n to store AI email analysis results.
 * Called after the AI analysis step in the n8n workflow.
 *
 * Expected body format (matching n8n workflow spec):
 * {
 *   emailId: string,
 *   priority: "haute" | "normale" | "basse",
 *   intent: string,           // e.g. "demande_devis", "suivi_contrat", "information"
 *   urgencyScore: number,     // 0-10
 *   summary: string,
 *   replySuggestion?: string,
 *   suggestedTask?: string,
 *   sentiment?: string,       // "positif" | "neutre" | "negatif"
 *   productsDetected?: string[],
 *   actions?: Array<{ type: string; titre: string; priorite: string; details?: string }>,
 *   senderName?: string,
 *   senderCompany?: string,
 * }
 */
async function handler(req: Request) {
  const body = await req.json();

  const {
    emailId,
    priority,
    intent,
    urgencyScore,
    summary,
    replySuggestion,
    suggestedTask,
    sentiment,
    productsDetected,
    actions,
    senderName,
    senderCompany,
  } = body as {
    emailId: string;
    priority?: string;
    intent?: string;
    urgencyScore?: number;
    summary?: string;
    replySuggestion?: string;
    suggestedTask?: string;
    sentiment?: string;
    productsDetected?: string[];
    actions?: Array<{ type: string; titre: string; priorite: string; details?: string }>;
    senderName?: string;
    senderCompany?: string;
  };

  if (!emailId) {
    return NextResponse.json({ error: "emailId is required" }, { status: 400 });
  }

  const email = await prisma.email.findUnique({ where: { id: emailId } });
  if (!email) {
    return NextResponse.json({ error: "Email not found" }, { status: 404 });
  }

  // Map urgencyScore (0-10) to urgence level
  const urgence = urgencyScore !== undefined
    ? urgencyScore >= 7 ? "haute" : urgencyScore >= 4 ? "normale" : "basse"
    : priority ?? null;

  // Build the full analyseIA JSON for storage
  const analyseIA = {
    priority: priority ?? urgence,
    intent,
    urgencyScore,
    summary,
    replySuggestion,
    suggestedTask,
    sentiment,
    productsDetected,
    actions: actions ?? [],
    expediteurNom: senderName ?? "",
    expediteurEntreprise: senderCompany ?? "",
  };

  // Determine if action is required
  const actionRequise = !!(suggestedTask || (actions && actions.length > 0) || (urgencyScore && urgencyScore >= 7));

  // Update email with analysis
  await prisma.email.update({
    where: { id: emailId },
    data: {
      analyseIA: JSON.stringify(analyseIA),
      resume: summary ?? null,
      urgence,
      typeEmail: intent ?? email.typeEmail,
      sentiment: sentiment ?? null,
      actionRequise,
      actionTraitee: false,
      reponseProposee: replySuggestion ?? null,
      analyseStatut: "analyse",
      produitsMentionnes: productsDetected
        ? JSON.stringify(productsDetected)
        : null,
    },
  });

  // Update client derniereInteraction if linked
  if (email.clientId) {
    await prisma.client.update({
      where: { id: email.clientId },
      data: { derniereInteraction: new Date() },
    });
  }

  // Auto-create task from suggestedTask if present
  if (suggestedTask) {
    // Prevent duplicates
    const existingTask = await prisma.tache.findFirst({
      where: { emailId, statut: { not: "terminee" } },
    });

    if (!existingTask) {
      await prisma.tache.create({
        data: {
          titre: suggestedTask,
          type: "RELANCE_PROSPECT",
          priorite: urgence === "haute" ? "haute" : "normale",
          dateEcheance: new Date(
            Date.now() + (urgence === "haute" ? 1 : 7) * 24 * 60 * 60 * 1000,
          ),
          clientId: email.clientId ?? null,
          emailId,
          autoGenerated: true,
          sourceAuto: "n8n_email_analysis",
        },
      });
    }
  }

  revalidatePath("/emails");
  revalidatePath("/emails/urgent");
  revalidatePath("/relances");
  revalidatePath("/clients");
  revalidatePath("/");

  return NextResponse.json({
    success: true,
    emailId,
    analysisStored: true,
    taskCreated: !!suggestedTask,
  });
}

export const POST = withN8nAuth(handler);
