import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { validateN8nRequest } from "@/lib/n8n";
import type { CreateTaskBody } from "@/lib/types/n8n-integration";

export async function POST(req: Request) {
  if (!validateN8nRequest(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = (await req.json()) as CreateTaskBody;

  if (!body.client_id || !body.title) {
    return NextResponse.json(
      { error: "client_id and title are required" },
      { status: 400 },
    );
  }

  // Verify client exists
  const client = await prisma.client.findUnique({
    where: { id: body.client_id },
    select: { id: true },
  });

  if (!client) {
    return NextResponse.json({ error: "Client not found" }, { status: 404 });
  }

  const priorite = body.priority ?? "normale";

  const tache = await prisma.tache.create({
    data: {
      titre: body.title,
      clientId: body.client_id,
      type: "ADMIN",
      priorite,
      dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      autoGenerated: true,
      sourceAuto: "n8n_integration",
    },
  });

  return NextResponse.json({
    id: tache.id,
    client_id: tache.clientId,
    title: tache.titre,
    priority: tache.priorite,
    status: tache.statut,
    created_at: tache.dateCreation.toISOString(),
  });
}
