import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

// API endpoint pour declencher les automatisations
// Peut etre appele manuellement depuis les parametres ou via un cron job
export async function POST() {
  const results = {
    echeancesContrats: 0,
    relancesProspects: 0,
    revisionsAnnuelles: 0,
    devClients: 0,
  };

  // 1. Alertes echeances contrats (6 mois avant)
  const sixMoisAvant = new Date();
  sixMoisAvant.setMonth(sixMoisAvant.getMonth() + 6);
  const contratsEcheance = await prisma.contrat.findMany({
    where: {
      statut: "actif",
      dateEcheance: {
        gte: new Date(),
        lte: sixMoisAvant,
      },
    },
    include: { client: true },
  });

  for (const contrat of contratsEcheance) {
    // Verifier si une tache existe deja pour cette echeance
    const existingTask = await prisma.tache.findFirst({
      where: {
        clientId: contrat.clientId,
        sourceAuto: "echeance_contrat",
        statut: { in: ["a_faire", "en_cours"] },
        titre: { contains: contrat.typeProduit },
      },
    });

    if (!existingTask) {
      await prisma.tache.create({
        data: {
          clientId: contrat.clientId,
          titre: `Renegociation ${contrat.typeProduit} - ${contrat.client.raisonSociale}`,
          description: `Contrat ${contrat.numeroContrat ?? ""} arrive a echeance le ${contrat.dateEcheance?.toLocaleDateString("fr-FR")}. Preparer le renouvellement.`,
          type: "ECHEANCE_CONTRAT",
          priorite: "haute",
          dateEcheance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // dans 30 jours
          autoGenerated: true,
          sourceAuto: "echeance_contrat",
        },
      });
      results.echeancesContrats++;
    }
  }

  // 2. Relances prospects automatiques (30/60/90 jours)
  const prospects = await prisma.client.findMany({
    where: {
      statut: "prospect",
      deals: {
        some: {
          etape: { in: ["PROSPECT_IDENTIFIE", "QUALIFICATION"] },
        },
      },
    },
    include: {
      deals: {
        where: { etape: { in: ["PROSPECT_IDENTIFIE", "QUALIFICATION"] } },
        orderBy: { dateCreation: "desc" },
        take: 1,
      },
    },
  });

  for (const prospect of prospects) {
    const lastDeal = prospect.deals[0];
    if (!lastDeal) continue;

    const daysSinceCreation = Math.floor(
      (Date.now() - lastDeal.dateCreation.getTime()) / (1000 * 60 * 60 * 24)
    );

    // Relance a 30, 60, 90 jours
    const relanceDays = [30, 60, 90];
    for (const days of relanceDays) {
      if (daysSinceCreation >= days - 2 && daysSinceCreation <= days + 2) {
        const existingRelance = await prisma.tache.findFirst({
          where: {
            clientId: prospect.id,
            sourceAuto: "relance_prospect",
            statut: { in: ["a_faire", "en_cours"] },
            titre: { contains: `J+${days}` },
          },
        });

        if (!existingRelance) {
          await prisma.tache.create({
            data: {
              clientId: prospect.id,
              titre: `Relance prospect J+${days} - ${prospect.raisonSociale}`,
              description: `Prospect non signe depuis ${days} jours. Relancer pour avancer dans le pipeline.`,
              type: "RELANCE_PROSPECT",
              priorite: days >= 90 ? "haute" : "normale",
              dateEcheance: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
              autoGenerated: true,
              sourceAuto: "relance_prospect",
            },
          });
          results.relancesProspects++;
        }
      }
    }
  }

  // 3. Revision annuelle clients actifs
  const clientsActifs = await prisma.client.findMany({
    where: {
      statut: "client_actif",
    },
    include: {
      contrats: {
        where: { statut: "actif" },
        orderBy: { dateEffet: "asc" },
        take: 1,
      },
    },
  });

  for (const client of clientsActifs) {
    const premierContrat = client.contrats[0];
    if (!premierContrat) continue;

    const dateEffet = new Date(premierContrat.dateEffet);
    const now = new Date();
    const anniversaire = new Date(dateEffet);
    anniversaire.setFullYear(now.getFullYear());

    // Si l'anniversaire approche (dans les 30 prochains jours)
    const joursAvant = Math.floor((anniversaire.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    if (joursAvant >= 0 && joursAvant <= 30) {
      const existingRevision = await prisma.tache.findFirst({
        where: {
          clientId: client.id,
          sourceAuto: "revision_annuelle",
          statut: { in: ["a_faire", "en_cours"] },
          dateCreation: { gte: new Date(now.getFullYear(), 0, 1) },
        },
      });

      if (!existingRevision) {
        await prisma.tache.create({
          data: {
            clientId: client.id,
            titre: `Revision annuelle - ${client.raisonSociale}`,
            description: `Audit rapide annuel. Verifier les contrats, les besoins et proposer des ameliorations.`,
            type: "REVISION_ANNUELLE",
            priorite: "normale",
            dateEcheance: anniversaire,
            autoGenerated: true,
            sourceAuto: "revision_annuelle",
          },
        });
        results.revisionsAnnuelles++;
      }
    }
  }

  // 4. Developpement client (6 mois apres signature)
  const dealsSignes = await prisma.deal.findMany({
    where: {
      etape: "SIGNATURE",
      dateSignature: {
        gte: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000),
        lte: new Date(Date.now() - 170 * 24 * 60 * 60 * 1000),
      },
    },
    include: { client: true },
  });

  for (const deal of dealsSignes) {
    const existingDev = await prisma.tache.findFirst({
      where: {
        clientId: deal.clientId,
        sourceAuto: "dev_client",
        statut: { in: ["a_faire", "en_cours"] },
      },
    });

    if (!existingDev) {
      await prisma.tache.createMany({
        data: [
          {
            clientId: deal.clientId,
            titre: `Audit dirigeant - ${deal.client.raisonSociale}`,
            type: "AUDIT_DIRIGEANT",
            priorite: "haute",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
          {
            clientId: deal.clientId,
            titre: `Optimisation retraite - ${deal.client.raisonSociale}`,
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
        ],
      });
      results.devClients++;
    }
  }

  return NextResponse.json({
    success: true,
    results,
    timestamp: new Date().toISOString(),
  });
}
