import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Pencil, Mail, Phone, MapPin, Building2, ArrowUpRight, ArrowDownLeft, MessageSquare, Shield, UserCheck, Handshake, Calendar, TrendingUp, Clock, FileText, Target, CheckCircle2, Sparkles, ShoppingBag } from "lucide-react";
import { STATUTS_CLIENT, TYPES_PRODUITS, ETAPES_PIPELINE, PRIORITES, STATUTS_DIRIGEANT, CATEGORIES_RESEAU } from "@/lib/constants";
import { format } from "date-fns";
import { ClientEmailHistory } from "@/components/clients/ClientEmailHistory";
import { fr } from "date-fns/locale";
import { calculerScoreProspect, getScoreColor, getScoreLabel } from "@/lib/scoring/prospect";
import { calculerPotentielCA } from "@/lib/scoring/potentiel";
import { calculerCouverture360, getCouvertureColor } from "@/lib/scoring/couverture360";
import { persisterScoresClient } from "@/lib/scoring/persist";
import { calculerProchainesActions } from "@/lib/scoring/next-actions";
import { NextActionWidget } from "@/components/clients/NextActionWidget";
import { CommercialMemoryCard } from "@/components/clients/CommercialMemoryCard";

export default async function ClientDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  const client = await prisma.client.findUnique({
    where: { id },
    include: {
      contrats: {
        include: { compagnie: true },
        orderBy: { dateEffet: "desc" },
      },
      deals: {
        orderBy: { dateMaj: "desc" },
      },
      taches: {
        where: { statut: { in: ["a_faire", "en_cours"] } },
        orderBy: { dateEcheance: "asc" },
      },
      emails: {
        orderBy: { dateEnvoi: "desc" },
        take: 50,
        select: {
          id: true,
          sujet: true,
          expediteur: true,
          destinataires: true,
          dateEnvoi: true,
          direction: true,
          extrait: true,
          resume: true,
          analyseStatut: true,
          analyseIA: true,
          typeEmail: true,
          urgence: true,
          sentiment: true,
          actionRequise: true,
          actionTraitee: true,
          reponseProposee: true,
          produitsMentionnes: true,
          notes: true,
          threadId: true,
          scoreRelevance: true,
          dateMaj: true,
        },
      },
      dirigeant: true,
      prescripteur: true,
    },
  });

  if (!client) notFound();

  // Fetch completed tasks for the timeline
  const tachesTerminees = await prisma.tache.findMany({
    where: { clientId: id, statut: "terminee" },
    orderBy: { dateRealisation: "desc" },
    take: 20,
  });

  // Detect sales opportunities from emails with products mentioned
  const hasOpportunity = client.emails.some((e) => {
    if (!e.produitsMentionnes) return false;
    try {
      const produits = JSON.parse(e.produitsMentionnes);
      return Array.isArray(produits) && produits.length > 0;
    } catch { return false; }
  });

  // Build timeline events
  type TimelineEvent = { date: Date; type: string; icon: string; title: string; detail?: string; color: string };
  const timeline: TimelineEvent[] = [];

  // Contrats signed
  for (const c of client.contrats) {
    const typeConfig = TYPES_PRODUITS[c.typeProduit as keyof typeof TYPES_PRODUITS];
    timeline.push({
      date: c.dateEffet,
      type: "contrat",
      icon: "FileText",
      title: `Contrat ${typeConfig?.label ?? c.typeProduit}`,
      detail: c.statut === "actif" ? "Signe et actif" : c.statut === "resilie" ? "Resilie" : c.statut,
      color: "#8B5CF6",
    });
  }

  // Deals
  for (const d of client.deals) {
    const etapeConfig = ETAPES_PIPELINE.find((e) => e.id === d.etape);
    timeline.push({
      date: d.dateCreation,
      type: "deal",
      icon: "Target",
      title: `Deal: ${d.titre}`,
      detail: etapeConfig?.label ?? d.etape,
      color: etapeConfig?.color ?? "#F59E0B",
    });
    if (d.dateSignature) {
      timeline.push({
        date: d.dateSignature,
        type: "signature",
        icon: "CheckCircle2",
        title: `Signature: ${d.titre}`,
        color: "#10B981",
      });
    }
  }

  // Tasks completed
  for (const t of tachesTerminees) {
    timeline.push({
      date: t.dateRealisation ?? t.dateCreation,
      type: "tache",
      icon: "CheckCircle2",
      title: t.titre,
      detail: t.autoGenerated ? "Auto" : "Manuel",
      color: "#3B82F6",
    });
  }

  // All emails (not just high-relevance)
  for (const e of client.emails) {
    timeline.push({
      date: e.dateEnvoi,
      type: "email",
      icon: "Mail",
      title: e.sujet,
      detail: e.direction === "sortant" ? `Envoye a ${e.destinataires.replace(/[[\]"]/g, "")}` : e.expediteur,
      color: "#06B6D4",
    });

    // AI analysis event
    if (e.analyseStatut === "analyse" && e.resume) {
      timeline.push({
        date: e.dateMaj ?? e.dateEnvoi,
        type: "analyse",
        icon: "Sparkles",
        title: `Analyse IA : ${e.resume.slice(0, 80)}${e.resume.length > 80 ? "..." : ""}`,
        detail: e.urgence === "haute" ? "Urgent" : e.urgence ?? undefined,
        color: "#F59E0B",
      });
    }
  }

  // Sort by date descending
  timeline.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  const statutConfig = STATUTS_CLIENT.find((s) => s.id === client.statut);
  const caRecurrent = client.contrats
    .filter((c) => c.statut === "actif")
    .reduce((sum, c) => sum + (c.commissionAnnuelle ?? 0), 0);
  const categorieReseau = CATEGORIES_RESEAU.find((c) => c.id === client.categorieReseau);
  // Persist scores (uses 24h cooldown, or computes if missing)
  let scores: { scoreProspect: number; potentielCA: number; scoreCouverture: number };
  try {
    scores = await persisterScoresClient(client.id);
  } catch {
    scores = {
      scoreProspect: calculerScoreProspect(client, client.contrats),
      potentielCA: calculerPotentielCA(client, client.contrats),
      scoreCouverture: calculerCouverture360(client.contrats).score,
    };
  }
  const { scoreProspect: score, potentielCA: potentiel, scoreCouverture } = scores;
  const scoreColor = getScoreColor(score);
  const couvertureColor = getCouvertureColor(scoreCouverture);

  // Compute next actions
  const nextActions = calculerProchainesActions({
    ...client,
    scoreCouverture,
    contrats: client.contrats,
    taches: client.taches,
    emails: client.emails,
    deals: client.deals,
    dirigeant: client.dirigeant,
  });

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold">{client.raisonSociale}</h1>
            <Badge
              variant="outline"
              style={{ borderColor: statutConfig?.color, color: statutConfig?.color }}
            >
              {statutConfig?.label}
            </Badge>
            {categorieReseau && (
              <Badge variant="secondary" className="text-[10px]" style={{ backgroundColor: categorieReseau.color + "20", color: categorieReseau.color }}>
                Reseau: {categorieReseau.label}
              </Badge>
            )}
            {hasOpportunity && (
              <Badge variant="outline" className="text-[10px] bg-emerald-50 text-emerald-700 border-emerald-300 gap-1">
                <ShoppingBag className="h-2.5 w-2.5" />
                Opportunite commerciale
              </Badge>
            )}
          </div>
          <p className="text-muted-foreground mt-1">
            {client.civilite} {client.prenom} {client.nom}
            {client.formeJuridique && ` \u2014 ${client.formeJuridique}`}
          </p>
        </div>
        <Link href={`/clients/${id}/modifier`}>
          <Button variant="outline" size="sm">
            <Pencil className="h-4 w-4 mr-2" />
            Modifier
          </Button>
        </Link>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold">{client.contrats.filter((c) => c.statut === "actif").length}</p>
            <p className="text-xs text-muted-foreground">Contrats actifs</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold">
              {new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(caRecurrent)}
            </p>
            <p className="text-xs text-muted-foreground">Commission annuelle</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold">{client.nbSalaries ?? "-"}</p>
            <p className="text-xs text-muted-foreground">Salaries</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold">{client.deals.length}</p>
            <p className="text-xs text-muted-foreground">Opportunites</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold" style={{ color: scoreColor }}>{score}</p>
            <p className="text-xs text-muted-foreground">Score ({getScoreLabel(score)})</p>
          </CardContent>
        </Card>
        {potentiel > 0 && (
          <Card>
            <CardContent className="pt-4">
              <p className="text-2xl font-bold text-emerald-600">
                {new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(potentiel)}
              </p>
              <p className="text-xs text-muted-foreground">Potentiel CA</p>
            </CardContent>
          </Card>
        )}
        <Card>
          <CardContent className="pt-4">
            <p className="text-2xl font-bold" style={{ color: couvertureColor }}>{scoreCouverture}%</p>
            <p className="text-xs text-muted-foreground">Couverture 360</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="space-y-4">
          <NextActionWidget actions={nextActions} />

          <CommercialMemoryCard
            temperatureCommerciale={client.temperatureCommerciale}
            produitsDiscutes={client.produitsDiscutes}
            objectionsConnues={client.objectionsConnues}
            besoinsIdentifies={client.besoinsIdentifies}
            dernierSignalDate={client.dernierSignalDate}
            dernierSignalResume={client.dernierSignalResume}
            nbSignaux={client.nbSignaux}
          />

          {/* Resume IA */}
          {client.resumeIA && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-amber-500" />
                  Resume IA
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground whitespace-pre-wrap space-y-1">
                  {client.resumeIA.split("\n").map((line, i) => (
                    <p key={i} className="text-xs">{line}</p>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          <Card>
            <CardHeader>
              <CardTitle className="text-base">Coordonnees</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              {client.email && (
                <div className="flex items-center gap-2">
                  <Mail className="h-4 w-4 text-muted-foreground" />
                  <a href={`mailto:${client.email}`} className="hover:underline">{client.email}</a>
                </div>
              )}
              {client.telephone && (
                <div className="flex items-center gap-2">
                  <Phone className="h-4 w-4 text-muted-foreground" />
                  <a href={`tel:${client.telephone}`} className="hover:underline">{client.telephone}</a>
                </div>
              )}
              {client.adresse && (
                <div className="flex items-center gap-2">
                  <MapPin className="h-4 w-4 text-muted-foreground" />
                  <span>{client.adresse}, {client.codePostal} {client.ville}</span>
                </div>
              )}
              {client.secteurActivite && (
                <div className="flex items-center gap-2">
                  <Building2 className="h-4 w-4 text-muted-foreground" />
                  <span>{client.secteurActivite}</span>
                </div>
              )}
              {client.siret && (
                <div className="text-muted-foreground">SIRET : {client.siret}</div>
              )}
              {client.conventionCollective && (
                <div className="text-muted-foreground">CCN : {client.conventionCollective}</div>
              )}
              {client.sourceAcquisition && (
                <div className="text-muted-foreground">Source : {client.sourceAcquisition}</div>
              )}
              {client.prescripteur && (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Handshake className="h-3 w-3" />
                  <Link href={`/prescripteurs/${client.prescripteur.id}`} className="hover:underline">
                    Prescripteur : {client.prescripteur.prenom} {client.prescripteur.nom}
                  </Link>
                </div>
              )}
              {client.derniereInteraction && (
                <div className="text-muted-foreground">
                  Dernier contact : {format(client.derniereInteraction, "dd MMM yyyy", { locale: fr })}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Couverture actuelle */}
          {(client.mutuelleActuelle || client.prevoyanceActuelle) && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base flex items-center gap-2">
                  <Shield className="h-4 w-4" />
                  Couverture actuelle
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                {client.mutuelleActuelle && (
                  <div>
                    <span className="text-muted-foreground">Mutuelle : </span>
                    <span>{client.mutuelleActuelle}</span>
                    {client.dateEcheanceMutuelle && (
                      <span className="text-xs text-muted-foreground ml-2">
                        (ech. {format(client.dateEcheanceMutuelle, "dd/MM/yyyy")})
                      </span>
                    )}
                  </div>
                )}
                {client.prevoyanceActuelle && (
                  <div>
                    <span className="text-muted-foreground">Prevoyance : </span>
                    <span>{client.prevoyanceActuelle}</span>
                    {client.dateEcheancePrevoyance && (
                      <span className="text-xs text-muted-foreground ml-2">
                        (ech. {format(client.dateEcheancePrevoyance, "dd/MM/yyyy")})
                      </span>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Dirigeant */}
          {client.dirigeant && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base flex items-center gap-2">
                  <UserCheck className="h-4 w-4" />
                  Dirigeant
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                <p className="font-medium">
                  {client.dirigeant.civilite} {client.dirigeant.prenom} {client.dirigeant.nom}
                </p>
                {client.dirigeant.statutProfessionnel && (
                  <p className="text-muted-foreground">
                    {STATUTS_DIRIGEANT.find((s) => s.id === client.dirigeant!.statutProfessionnel)?.label}
                  </p>
                )}
                {client.dirigeant.protectionActuelle && (
                  <p className="text-muted-foreground text-xs">{client.dirigeant.protectionActuelle}</p>
                )}
                {client.dirigeant.besoinsPatrimoniaux && (
                  <p className="text-muted-foreground text-xs">Besoins : {client.dirigeant.besoinsPatrimoniaux}</p>
                )}
                {!client.dirigeant.dateAuditDirigeant && (
                  <Badge variant="secondary" className="text-[10px] bg-amber-100 text-amber-700">
                    Audit dirigeant a faire
                  </Badge>
                )}
              </CardContent>
            </Card>
          )}

          {/* Veille concurrentielle */}
          {(client.courtierActuel || client.assureurActuelSante || client.motifChangement) && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base flex items-center gap-2">
                  <Shield className="h-4 w-4" />
                  Veille concurrentielle
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                {client.courtierActuel && (
                  <div>
                    <span className="text-muted-foreground">Courtier actuel : </span>
                    <span>{client.courtierActuel}</span>
                  </div>
                )}
                {client.assureurActuelSante && (
                  <div>
                    <span className="text-muted-foreground">Assureur sante : </span>
                    <span>{client.assureurActuelSante}</span>
                  </div>
                )}
                {client.dateDerniereRevision && (
                  <div>
                    <span className="text-muted-foreground">Derniere revision : </span>
                    <span>{format(client.dateDerniereRevision, "dd/MM/yyyy")}</span>
                  </div>
                )}
                {client.motifChangement && (
                  <Badge variant="secondary" className="text-[10px]">
                    Motif : {client.motifChangement}
                  </Badge>
                )}
              </CardContent>
            </Card>
          )}

          {/* Notes IA */}
          {client.noteEmails && (
            <Card>
              <CardHeader>
                <CardTitle className="text-base flex items-center gap-2">
                  <MessageSquare className="h-4 w-4" />
                  Notes IA (emails)
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-muted-foreground whitespace-pre-wrap space-y-1">
                  {client.noteEmails.split("\n").map((line, i) => (
                    <p key={i} className="text-xs">{line}</p>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        <div className="lg:col-span-2">
          <Tabs defaultValue="contrats">
            <TabsList>
              <TabsTrigger value="contrats">Contrats ({client.contrats.length})</TabsTrigger>
              <TabsTrigger value="pipeline">Pipeline ({client.deals.length})</TabsTrigger>
              <TabsTrigger value="taches">Taches ({client.taches.length})</TabsTrigger>
              <TabsTrigger value="emails">Emails ({client.emails.length})</TabsTrigger>
              <TabsTrigger value="historique">Historique</TabsTrigger>
            </TabsList>

            <TabsContent value="contrats" className="mt-4">
              {client.contrats.length === 0 ? (
                <p className="text-sm text-muted-foreground p-4">Aucun contrat</p>
              ) : (
                <div className="space-y-2">
                  {client.contrats.map((contrat) => {
                    const typeConfig = TYPES_PRODUITS[contrat.typeProduit as keyof typeof TYPES_PRODUITS];
                    return (
                      <Link key={contrat.id} href={`/contrats/${contrat.id}`} className="block">
                        <Card className="hover:bg-muted/30 transition-colors">
                          <CardContent className="py-3 flex items-center justify-between">
                            <div>
                              <div className="flex items-center gap-2">
                                <div
                                  className="w-2 h-2 rounded-full"
                                  style={{ backgroundColor: typeConfig?.color }}
                                />
                                <span className="font-medium text-sm">{typeConfig?.label}</span>
                              </div>
                              <p className="text-xs text-muted-foreground mt-1">
                                {contrat.compagnie?.nom} \u2014 {contrat.nomProduit}
                              </p>
                              {contrat.dateEcheance && (
                                <div className="flex items-center gap-1 mt-1">
                                  <Calendar className="h-3 w-3 text-muted-foreground" />
                                  <span className="text-[10px] text-muted-foreground">
                                    Echeance : {format(contrat.dateEcheance, "dd/MM/yyyy")}
                                  </span>
                                </div>
                              )}
                            </div>
                            <div className="text-right">
                              <p className="font-medium text-sm">
                                {new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(contrat.primeAnnuelle)}
                                /an
                              </p>
                              <Badge variant={contrat.statut === "actif" ? "default" : "secondary"} className="text-[10px]">
                                {contrat.statut}
                              </Badge>
                            </div>
                          </CardContent>
                        </Card>
                      </Link>
                    );
                  })}
                </div>
              )}
            </TabsContent>

            <TabsContent value="pipeline" className="mt-4">
              {client.deals.length === 0 ? (
                <p className="text-sm text-muted-foreground p-4">Aucune opportunite</p>
              ) : (
                <div className="space-y-2">
                  {client.deals.map((deal) => {
                    const etapeConfig = ETAPES_PIPELINE.find((e) => e.id === deal.etape);
                    return (
                      <Card key={deal.id}>
                        <CardContent className="py-3 flex items-center justify-between">
                          <div>
                            <p className="font-medium text-sm">{deal.titre}</p>
                            <Badge
                              variant="outline"
                              className="mt-1 text-[10px]"
                              style={{ borderColor: etapeConfig?.color, color: etapeConfig?.color }}
                            >
                              {etapeConfig?.label}
                            </Badge>
                          </div>
                          {deal.montantEstime && (
                            <p className="font-medium text-sm">
                              {new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(deal.montantEstime)}
                            </p>
                          )}
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>
              )}
            </TabsContent>

            <TabsContent value="taches" className="mt-4">
              {client.taches.length === 0 ? (
                <p className="text-sm text-muted-foreground p-4">Aucune tache en cours</p>
              ) : (
                <div className="space-y-2">
                  {client.taches.map((tache) => {
                    const prioriteConfig = PRIORITES.find((p) => p.id === tache.priorite);
                    return (
                      <Card key={tache.id}>
                        <CardContent className="py-3 flex items-center justify-between">
                          <div>
                            <div className="flex items-center gap-2">
                              <p className="font-medium text-sm">{tache.titre}</p>
                              {tache.autoGenerated && tache.emailId && (
                                <Badge variant="secondary" className="text-[10px] gap-0.5 bg-cyan-50 text-cyan-700 border-cyan-200">
                                  <Mail className="h-2.5 w-2.5" />
                                  Email
                                </Badge>
                              )}
                              {tache.autoGenerated && !tache.emailId && (
                                <Badge variant="secondary" className="text-[10px]">Auto</Badge>
                              )}
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">
                              Echeance : {format(tache.dateEcheance, "dd MMM yyyy", { locale: fr })}
                            </p>
                          </div>
                          <Badge
                            variant="outline"
                            style={{ borderColor: prioriteConfig?.color, color: prioriteConfig?.color }}
                          >
                            {prioriteConfig?.label}
                          </Badge>
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>
              )}
            </TabsContent>

            <TabsContent value="emails" className="mt-4">
              <ClientEmailHistory emails={client.emails} />
            </TabsContent>

            <TabsContent value="historique" className="mt-4">
              {timeline.length === 0 ? (
                <p className="text-sm text-muted-foreground p-4">Aucun evenement</p>
              ) : (
                <div className="relative">
                  <div className="absolute left-[15px] top-0 bottom-0 w-px bg-border" />
                  <div className="space-y-4">
                    {timeline.map((event, i) => {
                      const IconComponent = event.icon === "FileText" ? FileText
                        : event.icon === "Target" ? Target
                        : event.icon === "CheckCircle2" ? CheckCircle2
                        : event.icon === "Mail" ? Mail
                        : event.icon === "Sparkles" ? Sparkles
                        : Clock;
                      return (
                        <div key={i} className="flex gap-3 relative">
                          <div
                            className="w-[30px] h-[30px] rounded-full flex items-center justify-center flex-shrink-0 z-10"
                            style={{ backgroundColor: event.color + "20" }}
                          >
                            <IconComponent className="h-3.5 w-3.5" style={{ color: event.color }} />
                          </div>
                          <div className="flex-1 pt-1">
                            <p className="text-sm font-medium">{event.title}</p>
                            <div className="flex items-center gap-2 mt-0.5">
                              <span className="text-[10px] text-muted-foreground">
                                {format(event.date, "dd MMM yyyy", { locale: fr })}
                              </span>
                              {event.detail && (
                                <Badge variant="secondary" className="text-[10px]">{event.detail}</Badge>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  );
}
