"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { z } from "zod";

const dealSchema = z.object({
  clientId: z.string().min(1),
  titre: z.string().min(1),
  etape: z.string().default("PROSPECT_IDENTIFIE"),
  montantEstime: z.coerce.number().optional().nullable(),
  probabilite: z.coerce.number().int().min(0).max(100).optional().nullable(),
  produitsCibles: z.string().optional().nullable(),
  sourceProspect: z.string().optional().nullable(),
  prescripteurId: z.string().optional().nullable(),
  dateClosingPrev: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  assigneA: z.string().optional().nullable(),
  qualificationNotes: z.string().optional().nullable(),
  problematiqueDirigeant: z.string().optional().nullable(),
});

export async function createDeal(formData: FormData) {
  const raw = Object.fromEntries(formData.entries());
  const parsed = dealSchema.safeParse(raw);

  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors };
  }

  const data = parsed.data;
  await prisma.deal.create({
    data: {
      clientId: data.clientId,
      titre: data.titre,
      etape: data.etape,
      montantEstime: data.montantEstime ?? null,
      probabilite: data.probabilite ?? null,
      produitsCibles: data.produitsCibles || null,
      sourceProspect: data.sourceProspect || null,
      prescripteurId: data.prescripteurId || null,
      dateClosingPrev: data.dateClosingPrev ? new Date(data.dateClosingPrev) : null,
      notes: data.notes || null,
      assigneA: data.assigneA || null,
      qualificationNotes: data.qualificationNotes || null,
      problematiqueDirigeant: data.problematiqueDirigeant || null,
    },
  });

  revalidatePath("/pipeline");
}

export async function moveDeal(dealId: string, newEtape: string, motifPerte?: string) {
  const updateData: Record<string, unknown> = { etape: newEtape };

  if (newEtape === "SIGNATURE") {
    updateData.dateSignature = new Date();
    updateData.dateClosingReel = new Date();
  }

  if (newEtape === "ONBOARDING") {
    updateData.dateOnboarding = new Date();
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true, titre: true } });
    if (deal) {
      // Passer client en actif
      await prisma.client.update({
        where: { id: deal.clientId },
        data: { statut: "client_actif" },
      });
      // Creer taches onboarding automatiques
      await prisma.tache.createMany({
        data: [
          {
            clientId: deal.clientId,
            titre: "Completer fiche client",
            type: "ONBOARDING",
            priorite: "haute",
            dateEcheance: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "onboarding",
          },
          {
            clientId: deal.clientId,
            titre: "Planifier calendrier de suivi",
            type: "ONBOARDING",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "onboarding",
          },
          {
            clientId: deal.clientId,
            titre: "Rappel revision annuelle",
            type: "REVISION_ANNUELLE",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "revision_annuelle",
          },
        ],
      });
    }
  }

  if (newEtape === "DEVELOPPEMENT") {
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true } });
    if (deal) {
      await prisma.tache.createMany({
        data: [
          {
            clientId: deal.clientId,
            titre: "Audit dirigeant - protection et prevoyance",
            type: "AUDIT_DIRIGEANT",
            priorite: "haute",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
          {
            clientId: deal.clientId,
            titre: "Optimisation retraite dirigeant",
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
          {
            clientId: deal.clientId,
            titre: "Proposition epargne / assurance vie",
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
        ],
      });
    }
  }

  if (newEtape === "PERDU") {
    if (motifPerte) updateData.motifPerte = motifPerte;
    updateData.dateClosingReel = new Date();
  }

  await prisma.deal.update({
    where: { id: dealId },
    data: updateData,
  });

  revalidatePath("/pipeline");
  revalidatePath("/");
  revalidatePath("/relances");
}

export async function updateDealDetails(dealId: string, formData: FormData) {
  const raw = Object.fromEntries(formData.entries());

  await prisma.deal.update({
    where: { id: dealId },
    data: {
      qualificationNotes: (raw.qualificationNotes as string) || null,
      problematiqueDirigeant: (raw.problematiqueDirigeant as string) || null,
      checklistAudit: (raw.checklistAudit as string) || null,
      rapportAudit: (raw.rapportAudit as string) || null,
      syntheseClient: (raw.syntheseClient as string) || null,
      propositionCommerciale: (raw.propositionCommerciale as string) || null,
      comparatifAssureurs: (raw.comparatifAssureurs as string) || null,
      simulationCotisations: (raw.simulationCotisations as string) || null,
      assureurChoisi: (raw.assureurChoisi as string) || null,
      commissionsAttendues: raw.commissionsAttendues ? parseFloat(raw.commissionsAttendues as string) : null,
      documentsNotes: (raw.documentsNotes as string) || null,
    },
  });

  revalidatePath("/pipeline");
}

export async function deleteDeal(dealId: string) {
  await prisma.deal.delete({ where: { id: dealId } });
  revalidatePath("/pipeline");
}
