"use server";

import { prisma } from "@/lib/prisma";
import { getEnvironnement } from "@/lib/environnement";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { emitN8nEvent } from "@/lib/n8n";

const dealSchema = z.object({
  clientId: z.string().min(1),
  titre: z.string().min(1),
  etape: z.string().default("PROSPECT_IDENTIFIE"),
  montantEstime: z.coerce.number().optional().nullable(),
  probabilite: z.coerce.number().int().min(0).max(100).optional().nullable(),
  produitsCibles: z.string().optional().nullable(),
  sourceProspect: z.string().optional().nullable(),
  prescripteurId: z.string().optional().nullable(),
  dateClosingPrev: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  assigneA: z.string().optional().nullable(),
  qualificationNotes: z.string().optional().nullable(),
  problematiqueDirigeant: z.string().optional().nullable(),
});

export async function createDeal(formData: FormData) {
  const raw = Object.fromEntries(formData.entries());
  const parsed = dealSchema.safeParse(raw);

  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors };
  }

  const data = parsed.data;
  const env = await getEnvironnement();
  await prisma.deal.create({
    data: {
      environnement: env,
      clientId: data.clientId,
      titre: data.titre,
      etape: data.etape,
      montantEstime: data.montantEstime ?? null,
      probabilite: data.probabilite ?? null,
      produitsCibles: data.produitsCibles || null,
      sourceProspect: data.sourceProspect || null,
      prescripteurId: data.prescripteurId || null,
      dateClosingPrev: data.dateClosingPrev ? new Date(data.dateClosingPrev) : null,
      notes: data.notes || null,
      assigneA: data.assigneA || null,
      qualificationNotes: data.qualificationNotes || null,
      problematiqueDirigeant: data.problematiqueDirigeant || null,
    },
  });

  revalidatePath("/pipeline");
}

export async function moveDeal(dealId: string, newEtape: string, motifPerte?: string) {
  const env = await getEnvironnement();
  const updateData: Record<string, unknown> = { etape: newEtape };

  if (newEtape === "SIGNATURE") {
    updateData.dateSignature = new Date();
    updateData.dateClosingReel = new Date();
  }

  if (newEtape === "AUDIT") {
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true, client: { select: { raisonSociale: true } } } });
    if (deal?.client) {
      await prisma.tache.create({
        data: {
          environnement: env,
          clientId: deal.clientId,
          titre: `Préparer recommandation pour ${deal.client.raisonSociale}`,
          type: "ADMIN",
          priorite: "haute",
          dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
          autoGenerated: true,
          sourceAuto: "pipeline_audit",
        },
      });
    }
  }

  if (newEtape === "RECOMMANDATION") {
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true, client: { select: { raisonSociale: true } } } });
    if (deal?.client) {
      await prisma.tache.create({
        data: {
          environnement: env,
          clientId: deal.clientId,
          titre: `Relancer ${deal.client.raisonSociale} dans 7 jours`,
          type: "RELANCE_PROSPECT",
          priorite: "normale",
          dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
          autoGenerated: true,
          sourceAuto: "pipeline_recommandation",
        },
      });
    }
  }

  if (newEtape === "ONBOARDING") {
    updateData.dateOnboarding = new Date();
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true, titre: true } });
    if (deal) {
      // Passer client en actif
      await prisma.client.update({
        where: { id: deal.clientId },
        data: { statut: "client_actif" },
      });
      // Creer taches onboarding automatiques
      await prisma.tache.createMany({
        data: [
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Completer fiche client",
            type: "ONBOARDING",
            priorite: "haute",
            dateEcheance: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "onboarding",
          },
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Planifier calendrier de suivi",
            type: "ONBOARDING",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "onboarding",
          },
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Rappel revision annuelle",
            type: "REVISION_ANNUELLE",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "revision_annuelle",
          },
        ],
      });
    }
  }

  if (newEtape === "DEVELOPPEMENT") {
    const deal = await prisma.deal.findUnique({ where: { id: dealId }, select: { clientId: true } });
    if (deal) {
      await prisma.tache.createMany({
        data: [
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Audit dirigeant - protection et prevoyance",
            type: "AUDIT_DIRIGEANT",
            priorite: "haute",
            dateEcheance: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Optimisation retraite dirigeant",
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
          {
            environnement: env,
            clientId: deal.clientId,
            titre: "Proposition epargne / assurance vie",
            type: "DEV_CLIENT",
            priorite: "normale",
            dateEcheance: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
            autoGenerated: true,
            sourceAuto: "dev_client",
          },
        ],
      });
    }
  }

  if (newEtape === "PERDU") {
    if (motifPerte) updateData.motifPerte = motifPerte;
    updateData.dateClosingReel = new Date();
  }

  const updatedDeal = await prisma.deal.update({
    where: { id: dealId },
    data: updateData,
    include: { client: { select: { raisonSociale: true } } },
  });

  void emitN8nEvent({
    type: "deal.stage_changed",
    timestamp: new Date().toISOString(),
    payload: {
      dealId,
      dealTitre: updatedDeal.titre,
      clientId: updatedDeal.clientId,
      clientRaisonSociale: updatedDeal.client.raisonSociale,
      ancienneEtape: updatedDeal.etape, // Note: already updated, but logged for context
      nouvelleEtape: newEtape,
      montantEstime: updatedDeal.montantEstime,
      produitsCibles: updatedDeal.produitsCibles,
    },
  });

  revalidatePath("/pipeline");
  revalidatePath("/");
  revalidatePath("/relances");
}

export async function updateDeal(dealId: string, formData: FormData) {
  const raw = Object.fromEntries(formData.entries());
  const parsed = dealSchema.safeParse(raw);

  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors };
  }

  const data = parsed.data;
  await prisma.deal.update({
    where: { id: dealId },
    data: {
      clientId: data.clientId,
      titre: data.titre,
      montantEstime: data.montantEstime ?? null,
      probabilite: data.probabilite ?? null,
      produitsCibles: data.produitsCibles || null,
      sourceProspect: data.sourceProspect || null,
      prescripteurId: data.prescripteurId || null,
      dateClosingPrev: data.dateClosingPrev ? new Date(data.dateClosingPrev) : null,
      notes: data.notes || null,
      assigneA: data.assigneA || null,
      qualificationNotes: data.qualificationNotes || null,
      problematiqueDirigeant: data.problematiqueDirigeant || null,
    },
  });

  revalidatePath("/pipeline");
  revalidatePath("/");
}

export async function deleteDeal(dealId: string) {
  const session = await auth();
  if (!session?.user?.id) return { error: "Non authentifie" };
  await prisma.deal.delete({ where: { id: dealId } });
  revalidatePath("/pipeline");
}

export async function createContractsFromDeal(dealId: string, products: string[]) {
  const env = await getEnvironnement();
  const deal = await prisma.deal.findUnique({
    where: { id: dealId },
    select: { clientId: true, client: { select: { raisonSociale: true } } },
  });
  if (!deal) return;

  const TAUX_DEFAUT: Record<string, { apport: number; gestion: number }> = {
    SANTE_COLLECTIVE: { apport: 0.07, gestion: 0.06 },
    PREVOYANCE_COLLECTIVE: { apport: 0.10, gestion: 0.08 },
    PREVOYANCE_MADELIN: { apport: 0.20, gestion: 0.15 },
    SANTE_MADELIN: { apport: 0.12, gestion: 0.10 },
    RCP_PRO: { apport: 0.15, gestion: 0.12 },
    PER: { apport: 0.03, gestion: 0.007 },
    ASSURANCE_VIE: { apport: 0.03, gestion: 0.007 },
    PROTECTION_JURIDIQUE: { apport: 0.18, gestion: 0.15 },
  };

  for (const typeProduit of products) {
    const taux = TAUX_DEFAUT[typeProduit] ?? { apport: 0.05, gestion: 0.05 };
    await prisma.contrat.create({
      data: {
        environnement: env,
        clientId: deal.clientId,
        typeProduit,
        primeAnnuelle: 0,
        tauxCommApport: taux.apport,
        tauxCommGestion: taux.gestion,
        commissionAnnuelle: 0,
        dateEffet: new Date(),
        statut: "en_cours",
      },
    });
  }

  revalidatePath("/contrats");
  revalidatePath("/pipeline");
  revalidatePath("/clients");
  revalidatePath("/");
}
