import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { withN8nAuth } from "../middleware";

async function handler(req: Request) {
  const body = await req.json();

  const {
    titre,
    clientId,
    emailId,
    type,
    priorite,
    dateEcheance,
    description,
    sourceAuto,
  } = body as {
    titre: string;
    clientId?: string;
    emailId?: string;
    type: string;
    priorite?: string;
    dateEcheance?: string;
    description?: string;
    sourceAuto?: string;
  };

  if (!titre || !type) {
    return NextResponse.json(
      { error: "titre and type are required" },
      { status: 400 },
    );
  }

  const tache = await prisma.tache.create({
    data: {
      titre,
      clientId: clientId ?? null,
      emailId: emailId ?? null,
      type,
      priorite: priorite ?? "normale",
      dateEcheance: dateEcheance
        ? new Date(dateEcheance)
        : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      description: description ?? null,
      autoGenerated: true,
      sourceAuto: sourceAuto ?? "n8n",
    },
  });

  revalidatePath("/relances");

  return NextResponse.json({ id: tache.id, titre: tache.titre });
}

export const POST = withN8nAuth(handler);
